remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
layout: page
title: Tutoriales de Python para An치lisis de Se침ales y Sistemas
hide_hero: true
subtitle: The page subtitle
description: Tutoriales de Python para An치lisis de Se침ales y Sistemas
image: _includes/logoUTN.jpg
navbar: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
